### ISSUE TITLE
Update survey email so it works with charters

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#308] opened 2016-05-31 18:18 UTC
Discuss with Jeremy & Alex whether we can create 2 separate emails for charter and district since intro to each will be different.  Perhaps it's just an intro line that differs by school type?

**Comment by jtf621** [comment] 2016-05-31 22:49
@sarahsba please write the copy for the Charter school email.

**Comment by sarahsba** [comment] 2016-06-03 21:00
See email for charters here: https://docs.google.com/document/d/1rJZSTtX2x12rB0RRceC0PIVBRGMl6jFoxYvTAKGANds/edit

We should use this as the survey email for now and can swap it out when we send it to the districts.

**Comment by jtf621** [comment] 2016-06-16 18:59
duplicate of #318.  fixed in that issue and pull request #319.

**Closed by jtf621** 2016-06-16 18:59 UTC
