### ISSUE TITLE
School Descriptions must be entered by hand for all schools

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#103] opened 2015-05-19 12:45 UTC
Listed as 2-5 should be at least K-5 for the 2014 - 2015 school year.

Address is correct

website is correct

Mission statement is for Jordan.

**Comment by lemanal** [comment] 2015-05-19 21:45
Fixed Little river to be 0--5. Right now descriptions and images need to be added by hand for each school.

**Comment by lemanal** [comment] 2015-06-02 23:59
Dupe of #97

**Closed by lemanal** 2015-06-02 23:59 UTC
