### ISSUE TITLE
1000 N Duke St is in George Watts Priority Zone -- show on UI somehow

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#148] opened 2015-07-15 00:04 UTC

**Comment by adamajm** [comment] 2015-08-11 23:18
Adam, Colin, Alex discussed - On Assigned Tab, BRING to top of list all schools where the address in inside a zone, and a word in grey that indicates what TYPE OF ZONE it is.

**Comment by lemanal** [comment] 2015-08-25 22:30
Dupe of #135

**Closed by lemanal** 2015-08-25 22:30 UTC
Labels: ready
